name = "Cartography"
uuid = "b46f11dc-f210-4604-bfba-323c1ec968cb"
authors = ["Elias Carvalho <eliascarvdev@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Unitful = "1.19"
Zygote = "0.6"
julia = "1.9"
